### ISSUE TITLE
Fix fatal error on plugin activation

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-wait-lists#6] opened 2018-05-09 13:32 UTC
EE4 current master branch + EE4 wait lists master branch, on plugin activation:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to EventEspresso\core\domain\DomainBase::__construct() must be an instance of EventEspresso\core\domain\values\FilePath, string given in /srv/www/wordpress-default/public_html/wp-content/plugins/32-core/core/domain/DomainBase.php:56
Stack trace:
#0 [internal function]: EventEspresso\core\domain\DomainBase->__construct('/srv/www/wordpr...', '1.0.0.rc.092')
#1 /srv/www/wordpress-default/public_html/wp-content/plugins/32-core/core/EE_Registry.core.php(1262): ReflectionClass->newInstanceArgs(Array)
#2 /srv/www/wordpress-default/public_html/wp-content/plugins/32-core/core/EE_Registry.core.php(773): EE_Registry->_create_object('EventEspresso\\W...', Array, '', false)
#3 /srv/www/wordpress-default/public_html/wp-content/plugins/32-core/core/services/loaders/CoreLoader.php(116): EE_Registry->create('EventEspresso\\W...', Array, true, false, false, '')
#4 /srv/www/wordpress-default/public_html/wp-content/plugins/32-core/core/services/loaders/CachingLoader.php(143): EventEspresso\c in /srv/www/wordpress-default/public_html/wp-content/plugins/32-core/core/domain/DomainBase.php on line 56
```

**Comment by joshfeck** [comment] 2018-05-09 13:34
This might be an issue with EE4 core master because I can activate the Wait List add-on with the current release of EE4 core.

**Comment by nerrad** [comment] 2018-05-09 13:41
This is a duplicate of #3 and is fixed as a part of https://github.com/eventespresso/event-espresso-core/pull/386

**Closed by nerrad** 2018-05-09 13:41 UTC
Labels: status:duplicate
